# Generated by Django 4.0.4 on 2022-04-12 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uid', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=20)),
                ('category', models.CharField(max_length=20)),
                ('caste', models.CharField(max_length=30)),
                ('sub_caste', models.CharField(max_length=30)),
                ('nationality', models.CharField(max_length=100)),
                ('regNo', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=100)),
                ('div', models.CharField(max_length=20)),
                ('profile', models.CharField(max_length=200)),
                ('year', models.CharField(max_length=100)),
                ('degree', models.CharField(max_length=100)),
                ('course', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=100)),
            ],
        ),
    ]
