# Generated by Django 4.0.4 on 2022-04-11 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uid', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('regNo', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=100)),
                ('div', models.CharField(max_length=20)),
                ('profile', models.CharField(max_length=200)),
            ],
        ),
    ]
