# Generated by Django 4.0.4 on 2022-04-12 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateRequestModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('student_id', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('request_date', models.CharField(max_length=20)),
                ('issue_date', models.CharField(default='-', max_length=20)),
                ('approved', models.BooleanField(default=False)),
            ],
        ),
    ]
