# Generated by Django 4.0.4 on 2022-04-12 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_certificaterequestmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificaterequestmodel',
            name='url',
            field=models.CharField(default='#', max_length=200),
        ),
    ]
