# Generated by Django 4.0.4 on 2022-04-15 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_adminmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminmodel',
            name='mobile',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
