# Generated by Django 4.0.4 on 2022-04-15 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_adminmodel_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminmodel',
            name='profile',
            field=models.CharField(default='https://adityabodhankar.me/static/images/profile.jpeg', max_length=200),
            preserve_default=False,
        ),
    ]
