# Generated by Django 4.0.4 on 2022-04-15 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_adminmodel_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificaterequestmodel',
            name='status',
            field=models.CharField(default='Pending', max_length=30),
        ),
    ]
