# Generated by Django 4.0.4 on 2022-04-25 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_certificaterequestmodel_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificaterequestmodel',
            name='comment',
            field=models.CharField(default='', max_length=400),
        ),
    ]
