# Generated by Django 4.0.4 on 2022-04-25 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_certificaterequestmodel_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='certificaterequestmodel',
            old_name='issue_date',
            new_name='last_update_date',
        ),
        migrations.AlterField(
            model_name='certificaterequestmodel',
            name='comment',
            field=models.CharField(default='', max_length=400, null=True),
        ),
    ]
